src/accounts/urls.py
from django.conf.urls import url

from . import ajax
from . import views


app_name = 'accounts'


urlpatterns = [
    url('login/$', views.LoginView.as_view(), name='login'),
    url('register/$', views.RegisterView.as_view(), name='register'),
    url('confirm/(?P<uuid_key>[0-9a-zA-Z-]+)/$', views.ConfirmView.as_view()),
    # url('registration_success/$', views.registration_success_view),
    url('logout/$', views.logout_view, name='logout'),

    #ajax
    url('ajax_validate_email', ajax.check_email_existence),
]

src/cart/urls.py
from django.conf.urls import url

from . import views, ajaxviews


app_name = 'cart'


urlpatterns = [
    url('add/$', ajaxviews.add_to_cart, name='add_to_cart'),
    url('remove/$', ajaxviews.RemoveView.as_view(), name='remove'),
    url('$', views.CartItemsView.as_view(), name='cart_items'),
    # ajax
    # url('ajax/items/$', ajaxviews.get_cart_items),
]

src/kztrading/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

from django.conf.urls.static import static

from . import settings


urlpatterns = [
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^products/', include('products.urls', namespace='products')),
    url('^cart/', include('cart.urls', namespace='cart')),
    url('^orders/', include('orders.urls', namespace='orders')),
    url('^', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from . import views


app_name = 'products'



urlpatterns = [
    url('expose/$', views.ExposeProductView.as_view(), name='expose'),
    url('categories/$', views.CategoryListView.as_view(), name='categories'),
    url('items/(?P<id>[0-9]+)/$', views.ProductDetailView.as_view(), name='item'),
    url('items/', views.ProductsView.as_view(), name='items'),
    url('(?P<category>[a-zA-Z_]{1,128})/(?P<id>[0-9]+)/$',
        views.ProductDetailView.as_view(), name='category_item'),
    url('(?P<category_slug>[a-zA-Z_]{1,128})/', views.CategoryFilterProductView.as_view(), name='category'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}KZtrading{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static '/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    {% block base_css %}
        <link href="{% static '/css/base.css' %}" rel="stylesheet">
        <link href="{% static '/css/defaultnavbar.css' %}" rel="stylesheet">
        <link href="{% static '/css/defaultfooter.css' %}" rel="stylesheet">
    {% endblock %}
    {% block  additional_head %}{% endblock %}
</head>
<body>
{% block navbar %}
    {% include 'defaultnavbar.html' %}
{% endblock %}
{% block body %}{% endblock %}
{% block footer %}{% include 'defaultfooter.html' %}{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static '/bootstrap/bootstrap.min.js' %}"></script>
{% block additional_scripts %}{% endblock %}
</body>
</html>

src/templates/defaultfooter.html
<footer class="bd-footer font-small custom-full-footer pt-4">
    <div class="container-fluid text-center text-md-left custom-footer-top">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <h5 class="text-uppercase">Kyrgyzstan Trading</h5>
                <p>Footer content will be placed here</p>
            </div>
            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-3 mb-md-0 mb-3 ml-auto">
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#">Contact administration</a>
                    </li>
                    <li>
                        <a href="#">Vacancies</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center custom-footer-bottom py-2">© 2018 Copyright:
        KZtrading
    </div>
</footer>

src/templates/defaultnavbar.html
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'products:category' category_slug='all' as products_url %}
{% url 'products:categories' as categories_url %}
{% url 'products:expose' as expose_product_url %}
{% url 'cart:cart_items' as cart_items_url %}
{% url 'home:home' as home_url %}


<nav class="navbar navbar-expand-lg {# navbar-light bg-light #}navbar-light custom-full-navbar">
    <a class="navbar-brand" href="/"><i>KZtrading</i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle{% if request.get_full_path == home_url %} active {% endif %}"
                   href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {{ request.user.surname }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Incoming orders</a>
                    <a class="dropdown-item" href="#">Sales list</a>
                    <a class="dropdown-item" href="#">Purchases list</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ logout_url }}">Log out</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if request.get_full_path == expose_product_url %} active {% endif %}"
                   href="{{ expose_product_url }}">Expose</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link{% if request.get_full_path == register_url %} active {% endif %}"
                       href="{{ register_url }}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if request.get_full_path == login_url %} active {% endif %}"
                       href="{{ login_url }}">
                        Sign in
                    </a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link{% if request.get_full_path == goods_url %} active {% endif %}"
                   href="{{ products_url }}">Products
                </a>
            </li>
{#            <li class="nav-item dropdown">#}
{#                <a class="nav-link dropdown-toggle"#}
{#                   href="#" id="navbarDropdown" role="button"#}
{#                   data-toggle="dropdown"#}
{#                   aria-haspopup="true" aria-expanded="false">#}
{#                    Categories#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                    <a class="dropdown-item" href="#">Example</a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="">Example</a>#}
{#                </div>#}
{#            </li>#}
            <li class="nav-item">
                <a class="nav-link{% if request.get_full_path == categories_url%} active {% endif %}"
                   href="{{ categories_url }}">
                    Categories
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if request.session.purchases_amount %} active {% endif %}" href="{{ cart_items_url }}">
                    <i class="fas fa-shopping-cart"></i>
                    <sup id="purchases-amount">
                        {% if request.session.purchases_amount %}
                            {{ request.session.purchases_amount }}
                        {% else %}
                            empty
                        {% endif %}
                    </sup>
                </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 custom-navbar-button" type="submit">Search</button>
        </form>
    </div>
</nav>