src/cart/urls.py
from django.conf.urls import url

from . import views, ajaxviews


app_name = 'cart'


urlpatterns = [
    url('add/$', ajaxviews.add_to_cart, name='add_to_cart'),
    url('remove/$', ajaxviews.RemoveView.as_view(), name='remove'),
    url('$', views.CartItemsView.as_view(), name='cart_items'),
    # ajax
    # url('ajax/items/$', ajaxviews.get_cart_items),
]

src/kztrading/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

from django.conf.urls.static import static

from . import settings


urlpatterns = [
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^products/', include('products.urls', namespace='products')),
    url('^cart/', include('cart.urls', namespace='cart')),
    url('^orders/', include('orders.urls', namespace='orders')),
    url('^', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from . import views


app_name = 'products'



urlpatterns = [
    url('expose/$', views.ExposeProductView.as_view(), name='expose'),
    url('categories/$', views.CategoryListView.as_view(), name='categories'),
    url('items/(?P<id>[0-9]+)/$', views.ProductDetailView.as_view(), name='item'),
    url('items/', views.ProductsView.as_view(), name='items'),
    url('(?P<category>[a-zA-Z_]{1,128})/(?P<id>[0-9]+)/$',
        views.ProductDetailView.as_view(), name='category_item'),
    url('(?P<category_slug>[a-zA-Z_]{1,128})/', views.CategoryFilterProductView.as_view(), name='category'),
]

src/products/models.py
from functools import reduce
import uuid

from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


class ProductManager(models.Manager):

    def category(self, title):
        queryset = self.get_queryset().filter(category__title=title)
        return queryset

    def filter_id(self, id_list):
        if not id_list:
            return None
        query_list = [Q(id=item_id) for item_id in id_list]
        query= reduce(lambda total, item: total | item, query_list)
        queryset = self.model.objects.filter(query)
        return queryset


class Product(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    price = models.DecimalField(decimal_places=2, max_digits=10, null=False, blank=False)
    description = models.TextField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('products.Category', null=True, on_delete=models.SET_NULL)

    objects = ProductManager()

    def __str__(self):
        return str(self.title) + ' ' + str(self.seller.email)

    def get_absolute_url(self):
        return reverse('products:category_item', kwargs={'category': self.category.slug, 'id': self.id})


def build_image_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    new_name = str(uuid.uuid1())
    return 'products/images/' + new_name + '.' + ext


class Image(models.Model):
    image = models.ImageField(upload_to=build_image_upload_path)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.image.url).split('/')[-1]


def build_category_image_path(instance, name):
    ext = name.split('.')[-1]
    new_name = instance.slug
    return 'categories/images/' + new_name + '.' + ext


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=128, blank=False, null=False, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to=build_category_image_path)
    description = models.CharField(max_length=255)

    def __str__(self):
        return str(self.title)

src/products/forms.py
from django import forms

from .models import (
    Category,
    Product,
    Image
)


class ExposeProductForm(forms.Form):
    class FieldsAttrs:
        title = {
            'id': 'expose-product-title-id',
            'class': 'form-control'
        }
        price = {
            'id': 'expose-product-price-id',
            'class': 'form-control'
        }
        description = {
            'id': 'expose-product-description-id',
            'class': 'form-control',
            'style': 'resize: none'
        }
        # images = {
        #     'id': 'expose-product-images-id',
        #     'multiple': True,
        #     'class': 'custom-file-input'
        # }
        category = {
            'id': 'expose-product-category-id',
            'class': 'form-control'
        }

    title = forms.CharField(required=True,
                            widget=forms.TextInput(attrs=FieldsAttrs.title))
    price = forms.DecimalField(decimal_places=2, max_digits=10, required=True,
                               widget=forms.NumberInput(attrs=FieldsAttrs.price))
    description = forms.CharField(widget=forms.Textarea(attrs=FieldsAttrs.description))
    # images = forms.Field(widget=forms.ClearableFileInput(attrs=FieldsAttrs.images), required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True,
                                      widget=forms.Select(attrs=FieldsAttrs.category))

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.product = None
        super(ExposeProductForm, self).__init__(*args, **kwargs)

    def save(self):
        cleaned_data = self.cleaned_data
        product_data = {}
        for key in ('title', 'price', 'description', 'category'):
            item = cleaned_data.get(key)
            if item:
                product_data[key] = item
        product_data['seller'] = self.request.user
        product = Product(**product_data)
        product.save()
        self.product = product
        return product

    def clean(self):
        print('form clean#', self.cleaned_data)
        return self.cleaned_data

src/products/views.py
import code
from functools import reduce

from django.db.models import Q
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, FormView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


from .models import (
    Product,
    Category,
    Image,
)
from .forms import ExposeProductForm


class ProductsView(ListView):
    model = Product
    template_name = 'products/defaultlist.html'

    def get_queryset(self):
        category_title = self.kwargs.get('category')
        if category_title:
            queryset = self.model.objects.category(category_title)
        else:
            queryset = self.model.objects.all()
        if self.kwargs.get('search'):
            search_args = self.kwargs.get('search').split()
            query_list = [Q(title__icontains=item) for item in search_args]
            query = reduce(lambda total, item: total | item, query_list)
            queryset = queryset.filter(query).distinct()
        return queryset

    def get(self, *args, **kwargs):
        self.kwargs.update({key: value for key, value in self.request.GET.items()})
        print(self.kwargs)
        result = super().get(*args, **kwargs)
        return result


class ProductDetailView(DetailView):
    model = Product
    queryset = Product.objects
    template_name = 'products/productdetail.html'

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.queryset
        id = self.kwargs.get('id')
        try:
            item = queryset.get(id=id)
        except self.model.DoesNotExist as ex:
            raise Http404()
        return item


class CategoryListView(ListView):
    model = Category
    queryset = Category.objects.all()
    template_name = 'products/categories.html'


class CategoryFilterProductView(ListView):
    model = Product
    queryset = None
    template_name = 'products/productslist.html'
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        return super().get_context_data(object_list=None, **kwargs)

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        if category_slug == 'all':
            queryset = self.model.objects.all()
        else:
            queryset = self.model.objects.filter(category__slug=category_slug)
        search = self.kwargs.get('search')
        if search:
            search_args = search.split()
            query_params = [Q(item) for item in search_args]
            query = reduce(lambda total, item: total | item, query_params)
            queryset = queryset.filter(query).distinct()
        return queryset


def handle_files(files, product):
    images = files.getlist('images')
    for image in images:
        Image(image=image, product=product).save()


class ExposeProductView(LoginRequiredMixin, FormView):
    form_class = ExposeProductForm
    template_name = 'products/exposeproduct.html'

    def handle_no_permission(self):
        return redirect(reverse_lazy('accounts:login') + '?next={}'.format(self.request.path))

    def get_form(self, form_class=None):
        return self.form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        print('# valid')
        print('#', self.request.FILES)
        product = form.save()
        handle_files(self.request.FILES, product)
        return redirect(form.product.get_absolute_url())

    def form_invalid(self, form):
        return super().form_invalid(form)

src/products/templates/products/categories.html
{% extends 'base.html' %}

{% block body %}
    <div class="container mt-3">
        <div class="row">
            {% for category in object_list %}
                <div class="col-12 col-md-6 col-lg-4 mt-3 mb-3">
                    <div class="card  mx-auto" style="width: 320px; height: 400px;">
                        <img class="card-img-top mx-auto fix-img-size"
                             {% if category.image %}
                             src="{{ category.image.url}}"
                             {% endif %}
                             alt="{{ category.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ category.title }}</h5>
                            <p class="card-text">{{ category.description }}</p>
                        </div>
                        <button onclick="location.href='{% url 'products:category' category_slug=category.slug %}'"
                                align="center" class="btn card-footer">
                            Go to  {{ category.title }}
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/products/templates/products/defaultdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    {{ object.title }}
</div>
<div>
    {{ object.description }}
</div>
<div>
    ${{ object.price }}
</div>
<div>
    {{ object.seller }}
</div>
{% for image in object.image_set.all %}
    <img src="{{ image.image.url }}">
{% endfor %}
</body>
</html>

src/products/templates/products/defaultlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
</head>
<body>

{% for object in object_list %}
    <div>
        {{ object.title }}
    </div>
    <div>
        {{ object.description }}
    </div>
    <div>
        ${{ object.price }}
    </div>
    <div>
        {{ object.seller }}
    </div>
    <div>
        {{ object.category.title }}
    </div>
    <div>
        <a href="{% url 'products:item' id=object.id %}">link</a>
    </div>
    <hr>
{% endfor %}

</body>
</html>

src/products/templates/products/exposeproduct.html
{% extends 'base.html' %}

{% block body %}
    <div class="container mt-3 mx-auto col-12 col-md-8 col-lg-6 ">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <label for="expose-product-title-id">Title:</label>
            <div class="form-group">
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="expose-product-price-id">Price:</label>
                {{ form.price }}
            </div>
            <div class="form-group">
                <label for="expose-product-description-id">Description:</label>
                {{ form.description }}
            </div>
            <label for="expose-product-category-id">Category:</label>
            <div class="form-group">
                {{ form.category }}
            </div>
            <div class="custom-file">
                <input type="file" name="images" multiple id="expose-product-images-id" class="custom-file-input"/>
                <label class="custom-file-label" for="expose-product-images-id">Images:</label>
            </div>
            <div class="form-group mt-3">
                <input type="submit" class="btn btn-primary">
            </div>
        </form>
    </div>
{% endblock %}

src/products/templates/products/productdetail.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'products/productdetail.css' %}">
{% endblock %}

{% block body %}
    <div class="container mt-3">
        <div class="row">
            <div class="col-10 col-md-8 mx-auto mt-3">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in object.image_set.all %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in object.image_set.all %}
                        <div class="carousel-item{% if not forloop.counter0 %} active{% endif %}">
                            <div class="d-block w-100 image-container">
                                <img src="{{ image.image.url }}">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-10 col-md-4 mx-auto my-3">
                <h3 align="center" class="page-item product-header">{{ object.title.upper }}</h3>
                <div class="mt-4 product-activity-block">
                    <span class="price">${{ object.price }}</span>
                    <button onclick="addToCart({{ object.id }}, '{% url 'cart:add_to_cart' %}')" class="float-right btn btn-primary">Add to cart <i class="fas fa-shopping-cart"></i></button>
                </div>
                <div class="mt-4 product-description">
                    <p>
                        {{ object.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}
    <script src="{% static 'products/addtocart.js' %}"></script>
{% endblock %}

src/products/templates/products/productslist.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static '/products/productlist.css' %}">
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            {% for product in object_list %}
                <div class="col-12 col-md-6 col-lg-4 mt-3 mb-3">
                    <div class="card  mx-auto" style="width: 320px; height: 400px;">
                        <img class="card-img-top mx-auto fix-img-size"
                             src="{{ product.image_set.first.image.url }}" alt="{{ product.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.title }}</h5>
                            <p class="card-text">{{ product.description|slice:'35' }}...</p>
                            <span class="text btn font-weight-bold">${{ product.price }}</span>
                            <button onclick="addToCart({{ product.id }}, '{% url 'cart:add_to_cart' %}')"
                                    class="btn btn-primary float-right">
                                Add to cart <i class="fas fa-shopping-cart"></i>
                            </button>
                        </div>
                        <button align="center"
                                onclick="location.href='{% url 'products:category_item' category=product.category.slug id=product.id %}'"
                                class="btn card-footer">
                            show more
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% if is_paginated %}
        <div class="row my-3">
            <div class=" mx-auto" aria-label="pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% endif %}
                    <li class="page-item active">
                    <span class="page-link">
                    {{ page_obj.number }}
                    <span class="sr-only">(current)</span>
                    </span>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block additional_scripts %}
    <script src="{% static 'products/addtocart.js' %}"></script>
{% endblock %}