src/cart/urls.py
from django.conf.urls import url

from . import views, ajaxviews


app_name = 'cart'


urlpatterns = [
    url('add/$', ajaxviews.add_to_cart, name='add_to_cart'),
    url('remove/$', ajaxviews.RemoveView.as_view(), name='remove'),
    url('$', views.CartItemsView.as_view(), name='cart_items'),
    # ajax
    # url('ajax/items/$', ajaxviews.get_cart_items),
]

src/kztrading/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

from django.conf.urls.static import static

from . import settings


urlpatterns = [
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^products/', include('products.urls', namespace='products')),
    url('^cart/', include('cart.urls', namespace='cart')),
    url('^orders/', include('orders.urls', namespace='orders')),
    url('^', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart/views.py
from functools import reduce

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views.generic import ListView

from products.models import Product


class CartItemsView(LoginRequiredMixin, ListView):
    template_name = 'cart/cart.html'

    def handle_no_permission(self):
        return redirect(reverse_lazy('accounts:login') + '?next={}'.format(self.request.path))

    def get_queryset(self):
        items = self.request.session.get('cart_items')
        if not items:
            return None
        queryset = Product.objects.filter_id(items)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        object_list = object_list if object_list else self.object_list
        if object_list:
            total_cost = reduce(lambda total, current: total + current.price, object_list, 0)
            context['total_cost'] = total_cost
        return context

src/cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'cart/cart.css' %}">
{% endblock %}

{% block body %}
<div class="container my-5">
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">
                title
            </th>
            <th scope="col">
                id
            </th>
            <th scope="col">
                seller
            </th>
            <th scope="col">
                price
            </th>
            <th>

            </th>
        </tr>
        </thead>
        {% for object in object_list %}
            <tr class="item-row" id="item-row-{{ object.id }}">
                <td>
                    {{ object.title|slice:'20' }}
                </td>
                <td>
                    {{ object.id }}
                </td>
                <td>
                    {{ object.seller.email }}
                </td>
                <td>
                    ${{ object.price }}
                </td>
                <td>
                    <button type="button" onclick="order({{ object.id }}, '{% url 'orders:order' %}')" class="btn btn-primary float-right order-btn">order</button>
                    <button type="button" onclick="remove({{ object.id }}, '{% url 'cart:remove' %}')" class="btn btn-outline-danger float-right remove-btn">remove</button>
                </td>
            </tr>
        {% endfor %}
        <tr class="non-empty-cart-row"{% if not object_list %} style="display: none"{% endif %}>
            <td></td>
            <td></td>
            <td></td>
            <td class="total-cost">${{ total_cost }}</td>
            <td>
                <button type="button" onclick="orderAll('{% url 'orders:order' %}')"
                        class="btn btn-primary float-right order-btn">order all</button>
                <button type="button" onclick="removeAll('{% url 'cart:remove' %}')"
                        class="btn btn-outline-danger float-right remove-btn">remove all
                </button>
            </td>
        </tr>
        <tr class="empty-cart-row"{% if object_list %} style="display: none"{% endif %}>
            <td align=center colspan="5" class="no-orders-row">
                No orders
            </td>
        </tr>
    </table>
</div>
{% endblock %}

{% block additional_scripts %}
    <script src="{% static 'cart/requests.js' %}"></script>
{% endblock %}

src/cart/templates/cart/defaultcart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cart</title>
</head>
<body>
{% if object_list %}
    {% for object in object_list %}
        <div>
            object.title
        </div>
        <div>
            object.price
        </div>
        <div>
            object.description
        </div>
    {% endfor %}
{% else %}
    <div>
        Your cart is empty :(
    </div>
{% endif %}
</body>
</html>